"""
Open json files generated by exp1_minimize_detection_error.py script.
Parse results and analise correlation betweenn event and frame level metrics.
"""

import json
import os
import numpy as np
import matplotlib.pyplot as plt

json_folder_path = '/home/pans/datasets/DCASE2021/generated/exp1'


min_unix_time = 1617750293

json_files = [f for dp, dn, fn in os.walk(json_folder_path) for f in fn if int(f.split('.')[0]) > min_unix_time]
num_files = len(json_files)

mean_EP = np.empty(num_files)
mean_ER = np.empty(num_files)
mean_DOA = np.empty(num_files)
mean_FR = np.empty(num_files)
cost = np.empty(num_files)

for idx, j in enumerate(json_files):
    file_path = os.path.join(json_folder_path, j)
    with open(file_path) as f:
        data = json.load(f)
        mean_EP[idx] = data['result'][0]['mean_EP']
        mean_ER[idx] = data['result'][0]['mean_ER']
        mean_DOA[idx] = data['result'][0]['mean_DOA']
        mean_FR[idx] = data['result'][0]['mean_FR']
        cost[idx] = data['result'][0]['cost']
        # print(data)

plt.figure()
plt.plot(mean_EP, label='mean_EP')
plt.plot(mean_ER, label='mean_ER')
plt.plot(cost, label='cost')
plt.plot(mean_DOA, label='mean_DOA')
plt.plot(mean_FR, label='mean_FR')
plt.grid()
plt.legend()
plt.show()



